title: Ibraheem Abdul-Malik

version: 1.1.0

url: http://ibraheem.com
slug: Ibraheem
subtitle: Under Construction
description: A website made by Ibraheem Abdul-Malik

# Conversion
incremental: true

# Setup
sass:
  sass_dir: ./assets/scss
  style: compressed

baseurl: /
timezone: America/Los_Angeles
paginate: 6
paginate_path: blog/page/:num
permalink: /:categories/:title/

# Gems
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-gist

# Author
author:
  name: Ibraheem Abdul-Malik
  url: https://twitter.com/ibraheem4
  bio: Houston Texas 1986
  avatar: ibraheem.jpg
  email: ibraheem4@gmail.com

# Owner
owner:
  name: Ibraheem Abdul-Malik

# Project
github:
  username: ibraheem4
  repo: https://github.com/ibraheem4/ibraheem4.github.io

# Social
google:
  plus:
    custom_id: ibraheemabdulmalik4
  analytics:
    tracking_id: UA-27939534-4
  tagmanager:      
    id: GTM-BVJQ

twitter:
  username: ibraheem4

facebook:
  user_id: 7907713
  app_id: 275310882861610
  username: ibraheem4
  comments: true

instagram:
  username: ibraheem4_

disqus:
  shortname: ibraheem
  comments: true

# Files
include: 
  - "robots.txt"
  - "feed.xml"
  - "_pages"
exclude: 
  - ".gitignore"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"