title: ibraheem.com
future: true
published: true
show_drafts: false

version: 1.1.0

url: https://ibraheem.com
slug: Ibraheem
subtitle: Mostly posts about code.
description: This is my personal blog, since 2007.

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Conversion
incremental: true

# Setup
sass:
  sass_dir: ./assets/scss
  style: compressed

baseurl: /
timezone: America/Los_Angeles
permalink: :categories/:title/

# Plugins
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

paginate: 4

# Author
author:
  name: Ibraheem Abdul-Malik
  url: https://twitter.com/ibraheem4
  bio: Houston Texas 1986
  avatar: ibraheem.jpg
  email: ibraheem4@gmail.com

# Owner
owner:
  name: Ibraheem Abdul-Malik

# Project
github:
  username: ibraheem4
  repo: https://github.com/ibraheem4/ibraheem4.github.io

# Social
google:
  plus:
    custom_id: ibraheemabdulmalik4
  analytics:
    tracking_id: UA-27939534-4
  tagmanager:
    id: GTM-BVJQ

linkedin:
  username: ibraheem4

twitter:
  username: ibraheem4

facebook:
  user_id: 7907713
  app_id: 275310882861610
  username: ibraheem4
  comments: true

instagram:
  username: ibraheem4_

keybase:
  username: ibraheem

# Files
include:
  - "robots.txt"
  - "feed.xml"
  - "_pages"
exclude:
  - "vendor"
  - ".gitignore"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "gulpfile.js"
