# Dependencies
highlighter:        pygments

# Permalinks
permalink:          pretty

# Gems
gems:
- jemoji
- jekyll-sitemap

# Setup
title:              Ibraheem.com
tagline:            How to use the internet.
timezone:           America/Los_Angeles
paginate:           1
baseurl:            /
author:
  name:             Ibraheem Abdul-Malik
  url:              https://twitter.com/ibraheem4
  email:            ibraheem4@gmail.com

# Custom
version:            1.0.0
github:
  repo:             https://github.com/ibraheem4/ibraheem4.github.io

google:
  analytics:
    tracking_id:    UA-27939534-5