version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run:
        name: Yarn install
        command: yarn install --non-interactive
      - run:
        name: Bundle install
        command: bundle install
      - run:
        name: Jekyll build
        command: bundle exec jekyll build