version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Jekyll build
          command: bundle exec jekyll build